harshareddy794/HACKTOBERFEST2020

Python/word-of-number.py
created word representation of a number
=> Created word-of-number.py

C++/MatrixTranspose/tranpose.cpp
=> added matrix transpose

Java script/Data Structures/Linked_list.js, Java script/Data Structures/Queues.js, Java script/Data Structures/Stacks.js
Added some of the Data Structures in JS
=> Added some of the Data Structures in JS

Java script/Merge_sort_js/merge_sort.js, Java script/Merge_sort_js/merge_sort.md
Merge sort implementation in js
let’s first identify the problem, plan, and come up with a solution. Let’s take an example array [10, -1, 2, 5, 0, 6, 4, -5]. This is obviously an unsorted array. That is exactly our problem and we must sort this array using merge sort. Merge sort requires dividing the problem into smaller problems.
Notice that at each level we divide the array into two halves until we get bunch of single element arrays. This is the divide portion of the divide and conquer method. Then, we start merging and sorting the smaller arrays in a series of steps which is the conquer portion of divide and conquer.
=> added merge sort in javascript

README.md
When i tried opening you contribute link it was not opening so i changed it
=> Dead link changed to working link

Python/live_facial_recognition.py
This is all about running face recognition on live video from webcam.
Do add sample images and create changes accordingly.
=> Live stream facial recognition

C++/cocktailSort.cpp
=> added cocktail sort

C++/Shortest Route Algorithm/shortest route.cpp
I am added a file in the folder
=> Create shortest route.cpp

ShortestRoute Algorithms/shortest Path.cpp
Added file in the folder please review it
=> Create shortest Path.cpp

Python/MazeGenerator(Backtracking)/Maze_Generator.py
This is a Maze generating program which makes a unique square maze each and every time of a specified input size
=> Created Maze Generator in python using Backtracking

Python/YoutubeDownloader/Readme.md, Python/YoutubeDownloader/ytDownloader.py
I have added a script to download youtube videos using python program and a readme to describe about that program.
=> Youtube Video Downloader with Python

C++/Kruskal_Algorithm.cpp, C++/Possible_sum.cpp, C++/towerOfHanoi.cpp, C/Arr4 right shift.c, C/Array_in_C.c, C/Remove-Duplicates-from-Sorted-Array.c, C/Shuffle.c, C/Two-Arrays-And-Swaps.c, C/copyarray.c, C/merging_2_arrays.c, C/revering_array.c
Please accept my PR and help me contribute open source
=> added various programs

Python/datacleaning
This is a complete example of comparing variance threshold to the number of selected features.
=> DataCleaning

C++/Fibonacci/Fibonacci_series.c
It is a fibonacci series using recursive function to save time.
=> Fibonacci_series.c

C++/Fibonacci/fib_recursive.cpp
A cpp program to generate the Fibonacci series in a given limit using while loop and recursion.
=> Added fib_recursive.cpp

C++/Minimax_Algorithm/Minimax.cpp
Added Minimax algorithm used in Game theory
=> Added C++ algorithm

C++/Triangle_Pattern.cpp
Implemented a triangle printing pattern using C++
=> Create Triangle Pattern using C++

Python/Motion_detection/Detection.py, Python/Motion_detection/MotionDetection.md
Added Motion Detection in python
Python/Motion_detection/Detection.py
=> Added Motion Detection in python

C++/pascal.cpp
I have written a code on printing the pascal,s triancle. If you like it , please accept my pull request and merge it. If possible I would make more contributions in your file.
Thank you
=> Created a cpp file for pattern print

C/binarySearchTree.c
Implement Binary Search Tree algorithm in C
Hactoberfest
=> Implemented Binary search tree using structue in C

Java script/Recursive Palindrome/recursive-palindrome.js, Java script/Recursive Palindrome/recursive_palindrome.md
This is a recursive palindrome algo in JS. Thanks
=> added recursive palindrome algo

C/converter.c
this code can convert a three digit number to text
=> digit to text converter added

C++/Factorial/Factorial.cpp
I added the correct header file for the Factorial.cpp program, as well as improved the code readability. Did I do this correctly? This is technically my first pull request.
=> added correct header file and improved code readability

Python/Smile_detector/Smile_detector.py, Python/Smile_detector/haarcascade_eye.xml, Python/Smile_detector/haarcascade_frontalface_default.xml, Python/Smile_detector/haarcascade_smile.xml, Python/Smile_detector/readme.md
A python script for smile detection.
=> Added Smile_detector

C++/Overloading.cpp
=> Created Overloading.cpp

Python/neural_networks/neural_network_from_scratch.py
The python file attached serves as template. Current template is mainly designed for computer vision tasks.The dataset (.h5 files) is not added and it is purely dependent on user(like can be used for cats and dogs, pneumonia vs non pneumonia,etc.).
=> neural network from scratch with gradient descent

Python/medium_article_scraper/LICENCE, Python/medium_article_scraper/README.md, Python/medium_article_scraper/medium_scraper.py, Python/medium_article_scraper/requirements.txt
This is my second contribution as part of `HacktoberFest 2020`.
I've written a simple script to search for articles on `Medium.com` and scrape the results.
The results are then returned in handy `JSON` format (I love JSON 😆).
Nothin too spectacular, but can come in handy time to time.
Language: Python 3.5+
Contribution for #10
=> Add medium article scraper

Java script/Number_is_Prime/number_isPrime.js, Java script/Number_is_Prime/number_isPrime.md
Hello. This is a prime number checker. Thanks.
=> prime number checker

Java script/String/FormatMoney.js
=> Format Money

C++/SJF(Scheduling algo.)/Readme.md, C++/SJF(Scheduling algo.)/Shortest Job First Schedulling Algorithm(SJF - Non-Preemptive).cpp, C/Priority scheduling/Priority based Scheduling (Non - Preemptive).c, C/Priority scheduling/README.md
please accept my pull request of this issue #102
=> Adds sample i/o and time and space complexity

C/README.md, C/selection_sort.c, C/selection_sort/README.md, C/selection_sort/selection_sort.c
I have added the folder and the README file
=> added C implementation of selection sort algorithm

C/Eval_Postfix.c, C/bracket_balance.c
Hey there,
Please review and accept my PR.
Thank you.
=> Added Eval_Postfix.c and bracket_balance.c

C/LinearSearch.c
Created a Linear Search C Program which is used to find an element in an array
=> LinearSearch.c

Python/Web Scrapping/Beautifulsoup/main.py
=> Web Scrapping-Beautiful Soup added

C/matrix_operations.c
the basic matrix operations like addition, subtraction, Multiplication and transpose are added
=> matrix operations are added

Python/nbase-to-decimal-converter.py
I hope you enjoy this code ^_^
=> Create nbase-to-decimal-converter in Python

C/triangle.c
#102 
@harshareddy794 
C Program to print Number Triangle
Like the alphabet triangle, we can write the c program to print the number triangle. The number triangle can be printed in different ways.
Let's see the c example to print number triangle.
=> Print Number Triangle

C++/Backtracking/Black_and_White.cpp, C++/Dynamic Programming/First_n_Fibonacci_Numbers.cpp
Worked on issue#12  and Adding c++ codes.
=> Adding c++ solutions
